# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mp4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30)),
                ('link', models.CharField(default='', max_length=50)),
                ('image', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
